#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.22f1_9fdda2fe27ad"
#define UNITY_VERSION_FULL_NICE "2019.4.22f1 (9fdda2fe27ad)"
#define UNITY_VERSION_BLD 10476962
#define UNITY_VERSION_DATE 1614734676
#define UNITY_VERSION_WIN "2019.4.22.10476962"
#define UNITY_VERSION_BRANCH "2019.4/staging"
